//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bikbulatov_Laguage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public int DurationInSeconds { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public double Discount { get; set; }
        public string Description { get; set; }
        public string MainImagePath { get; set; }
    }
}
